branch-defaults:
  master:
    environment: proto
    group_suffix: null
global:
  application_name: ner-ms
  default_ec2_keyname: null
  default_platform: Docker 1.11.2
  default_region: eu-central-1
  profile: null
  sc: git
